version: '3'
services:
  raccoon-mh-github-io:
    container_name: raccoon-mh-github-io
    build: ../
    networks:
      - docker-nginx-network
    environment:
      POSTGRES_HOST : raccoon-mh-github-io-db
      POSTGRES_DB: raccoonmhdb
      POSTGRES_USER: raccoonmh
      POSTGRES_PASSWORD: pAZWWjTeLSztXKu
    depends_on:
      - raccoon-mh-github-io-db
    restart: unless-stopped

  raccoon-mh-github-io-db:
    image: postgres:latest
    volumes:
      - raccoon_mh_db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: raccoonmhdb
      POSTGRES_USER: raccoonmh
      POSTGRES_PASSWORD: pAZWWjTeLSztXKu
    networks:
      - docker-nginx-network

networks:
  docker-nginx-network:
    external: true

volumes:
  raccoon_mh_db: