name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true

      # 의존성 설치
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      # Jekyll 빌드 (Bulma Clean Theme 및 관련 설정이 Gemfile과 _config.yml에 반영되어 있다고 가정)
      - name: Build the site with Jekyll
        run: bundle exec jekyll build

      # 빌드된 _site 디렉토리를 GitHub Pages에 배포 (peaceiris/actions-gh-pages 액션 사용)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
